openapi: '3.0.0'
info:
  title: F1 Race Panel API
  description: The API used for F1 Race Panel (f1racepanel.com)
  contact:
    name: Daniel Luna
    email: api-support@f1racepanel.com
    url: https://danielluna.nyc
  version: 'v1'

servers:
  - url: https://api.f1racepanel.com/v1
    description: Production
  - url: https://staging.api.f1racepanel.com/v1
    description: Development

paths:
  "/drivers/{DriverID}":
    parameters:
      - $ref: "#/components/parameters/driverID"
    get:
      summary: "Get Driver"
      description: "Get information for a specific driver."
      tags:
        - "Drivers"
      responses:
        200:
          $ref: "#/components/responses/Driver"
        404:
          $ref: "#/components/responses/NotFound"
    post:
      summary: "Edit Driver"
      security:
        - AdminAuth: []
      tags:
        - "Drivers"
      responses:
        200:
          $ref: "#/components/responses/Driver"
        401:
          $ref: "#/components/responses/Unauthorized"
        404:
          $ref: "#/components/responses/NotFound"
      
  "/drivers":
    get:
      summary: "Get Multiple Drivers"
      tags:
        - "Drivers"
      parameters:
        - $ref: "#/components/parameters/limit"
        - $ref: "#/components/parameters/offset"
      responses:
        200:
          $ref: "#/components/responses/MultipleDrivers"
        404:
          $ref: "#/components/responses/NotFound"

  "/circuits":
    get:
      summary: "Get Circuits"
      tags:
        - "Circuits"
      parameters:
        - $ref: "#/components/parameters/limit"
        - $ref: "#/components/parameters/offset"
      responses:
        200:
          $ref: "#/components/responses/MultipleCircuits"
        404:
          $ref: "#/components/responses/NotFound"

  "/season/{Year}":
    get:
      summary: "Get Season Info"
      tags:
        - "Grand Prix Weekend"
      responses:
        404:
          $ref: "#/components/responses/NotFound"

  "/gp/{Year}/{Round}":
    get:
      summary: "Get Grand Prix Weekend"
      tags:
        - "Grand Prix Weekend"
      responses:
        404:
          $ref: "#/components/responses/NotFound"

  "/gp/{Year}/{Round}/{Session}":
    get:
      summary: "Get Grand Prix Session"
      tags:
        - "Grand Prix Weekend"
      responses:
        404:
          $ref: "#/components/responses/NotFound"

  "/login":
    get:
      summary: "Log In"
      tags:
        - "Admin"
      responses:
        401:
          $ref: "#/components/responses/Unauthorized"

components:
  securitySchemes:
    AdminAuth:
      type: apiKey
      in: header
      name: X-Auth
      description: "Authentication Token recieved after logging in."

  responses:
    Driver:
      description: "A driver."
      content:
        "application/json":
          schema:
            $ref: "#/components/schemas/Driver"

    MultipleDrivers:
      description: "An array of drivers."
      content:
        "application/json":
          schema:
            $ref: "#/components/schemas/Drivers"

    Circuit:
      description: "A circuit."
      content:
        "application/json":
          schema:
            $ref: "#/components/schemas/Circuit"

    MultipleCircuits:
      description: "An array of circuits."
      content:
        "application/json":
          schema:
            $ref: "#/components/schemas/Circuits"

    Unauthorized:
      description: "API Key is missing or invalid."
      content:
        "application/json":
          schema:
            $ref: "#/components/schemas/Error"

    NotFound:
      description: "The specified resource was not found."
      content:
        "application/json":
          schema:
            $ref: "#/components/schemas/Error"

  parameters:
    driverID:
      in: path
      name: DriverID
      description: "UUID of a specific driver."
      schema:
        type: string
        format: uuid
      required: true

    limit:
      in: query
      name: limit
      description: "The number of drivers to return."
      schema:
        type: integer
        default: 25
        minimum: 1
    offset:
      in: query
      name: offset
      description: "The number of items to skip before starting to collect the result set."
      schema:
        type: integer
        default: 0
        minimum: 0

  schemas:
    Driver:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: "F1 Race Panel Driver ID Number."
        name:
          type: string
          description: "Name of the driver."
        nationality:
          type: string
          description: "Nationality of the driver."
        dob:
          type: string
          format: date
          description: "Date of Birth of the driver."
      required:
        - id
        - name
        - nationality
        - dob

    Drivers:
      type: object
      properties:
        drivers:
          type: array
          items:
            $ref: "#/components/schemas/Driver"
        count:
          type: integer
          description: "Number of drivers in the array."
          minimum: 1
        offset:
          type: integer
          description: "Number of items skipped before starting the result set."
          minimum: 0
      required:
        - drivers
        - count

    CircuitLayout:
      type: object
      properties:
        name:
          type: string
          description: "Name of layout."
        first_year:
          type: integer
          description: "First year of the layout."
        last_year:
          type: integer
          description: "Last year of usage of the layout (if applicable)."
        track_length:
          type: number
          description: "Length of circuit in KM"
        race_lap_record:
          type: object
          properties:
            time:  
              type: string
              pattern: '^\d{1}:\d{2}.\d{3}$'
              example: '1:21.500'
              description: "Race lap record of the layout. Format is {minutes}:{seconds}.{milliseconds}"
            driver_id:
              type: string
              format: uuid
              description: "DriverID of the driver who set the fastest time"

    Circuit:
      type: object
      properties:
        name:
          type: string
          description: "Name of the circuit."
        country:
          type: string
          description: "ISO 3166-1 alpha-2 country code."
        date_opened:
          type: string
          format: date
          description: "Date the track first opened."
        layouts:
          type: array
          items:
            $ref: "#/components/schemas/CircuitLayout"

    Circuits:
      type: object
      properties:
        circuits:
          type: array
          items:
            $ref: "#/components/schemas/Circuit"
        count:
          type: integer
          description: "Number of circuits in the array."
          minimum: 1
        offset:
          type: integer
          description: "Number of items skipped before starting the result set."
          minimum: 0
      required:
        - drivers
        - count

    Error:
      type: object
      properties:
        code:
          type: integer
          description: "The HTTP status code."
          minimum: 400
          maximum: 599
        description:
          type: string
          description: "A short description of the cause of the error."
      required:
        - "code"
        - "description"