services:
  db:
    container_name: pg_db
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=f1racepanel
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped

  db-test:
    container_name: pg_db_test
    image: postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=f1racepanel
    ports:
      - 5432:5432
    volumes:
      - postgres_data_test:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers-docker.json
    restart: unless-stopped
    volumes:
      - ./pgadmin.json:/pgadmin4/servers-docker.json

volumes:
  postgres_data:
  postgres_data_test:
